// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return FirebaseOptions(
          apiKey: 'AIzaSyBc8Uvfxld284RO3J82q4cN19_j3-9bfZs',
          appId: '1:22303843381:android:aced234bb1e7bcc1f23d7c',
          messagingSenderId: '22303843381',
          projectId: 'rebooked-8fe1e',
          storageBucket: 'rebooked-8fe1e.firebasestorage.app',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc8Uvfxld284RO3J82q4cN19_j3-9bfZs',
    appId: '1:22303843381:android:aced234bb1e7bcc1f23d7c',
    messagingSenderId: '22303843381',
    projectId: 'rebooked-8fe1e',
    storageBucket: 'rebooked-8fe1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY94Vd2kBZJNSx0xjRoWk002N3b7U_6kY',
    appId: '1:22303843381:ios:383ee949ca41eb21f23d7c',
    messagingSenderId: '22303843381',
    projectId: 'rebooked-8fe1e',
    storageBucket: 'rebooked-8fe1e.firebasestorage.app',
    iosBundleId: 'com.rebooked.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtTlIA6s4IvMKajxoiW2nu6pr1Fa0lkww',
    appId: '1:22303843381:web:814ea168d360fddff23d7c',
    messagingSenderId: '22303843381',
    projectId: 'rebooked-8fe1e',
    authDomain: 'rebooked-8fe1e.firebaseapp.com',
    storageBucket: 'rebooked-8fe1e.firebasestorage.app',
  );
}
